### ISSUE TITLE
[Product Home] Style Columns on product home

### ISSUE THREAD

**Issue by mhaack** [hlxsites/danaher-ls-aem#562] opened 2023-12-07 10:38 UTC
https://www.figma.com/file/fgBV6T1rkYBvzQYzwwUnFt/Bioscience-hub-3?type=design&node-id=22300-458920&mode=dev

![Screenshot 2023-12-07 at 11 38 19](https://github.com/hlxsites/danaher-ls-aem/assets/2643450/398a5eb9-0966-4201-988b-35c5be2eeda8)

**Comment by duynguyen** [comment] 2023-12-12 10:37
as discussed, this would be resolved by the carousel (one slide variant).
@amlan18041996 assigned this to you to confirm.

**Comment by duynguyen** [comment] 2023-12-12 10:39
actually a duplicate of #509 , hence closing.

**Closed by duynguyen** 2023-12-12 10:39 UTC
Labels: frontend
