### ISSUE TITLE
UX Feedback and Button text alignment

### ISSUE THREAD

**Issue by ADeLaura** [hlxsites/danaher-ls-aem#100] opened 2023-09-18 18:26 UTC
- [ ] Text in the purple outline CTAs is not horizontally aligned in the button they are shifted higher than center. Live site is correct

- [ ] Button text is not horizontally center. The text is 5 pixels higher in the button -

- [x] Font weights do not match. Circle call outs are a bolder font and should be thinner. The headlines for the sections should be bolder. (screenshot has stage on left and prod on right)

- [x] We do not have the sticky form of the navigation as the user scrolls down. See screenshots -> known enhancement in #45 (fixed by #102)

- [x] Lowest section “Our Scientist are leading…” the button has a white background. It does not on live site -> known enhancement in #68 (fixed by #99)

- [x] Card Highlight animation is a bit harsh on Franklin. The live site has a scale with a soft ending. Where as the franklin version is scales quickly and ends more abruptly

- [ ] Mobile View – Spacing between top 3 cards Trending, engineering…) is very tight compared to the live site.

![Screenshot 2023-09-18 at 2 31 16 PM](https://github.com/hlxsites/danaher-ls-aem/assets/124819426/3a5c8d92-c6f3-4a4d-8aea-4a834472349b)

**Comment by dicagno** [comment] 2023-09-19 05:42
@ADeLaura thank you so much for the feedback. I broke the issue down into different steps, to make it easier for us to check and address the issues.

@mhaack @duynguyen assigned to you as well, so we can all check. I will start by checking the issues that i can tackle in my currently open PR (#99)

**Comment by mhaack** [comment] 2023-09-19 08:06
> We do not have the sticky form of the navigation as the user scrolls down. See screenshot

Should be address via #102 

> Lowest section “Our Scientist are leading…” the button has a white background. It does not on live site

Should be addressed via #99

**Comment by duynguyen** [comment] 2023-09-19 11:36
@ADeLaura - could you please clarify the 2 below points? with screenshot would be the best, as we could not reproduce them.

- Text in the purple outline CTAs is not horizontally aligned in the button they are shifted higher than center. Live site is correct
- Button text is not horizontally center. The text is 5 pixels higher in the button

**Comment by duynguyen** [comment] 2023-09-19 14:15
@ADeLaura - looks like the screenshot are not included in your reply by email. Could you please post a direct comment here with the picture?

**Comment by davenichols-DHLS** [comment] 2023-09-19 14:39
![image](https://github.com/hlxsites/danaher-ls-aem/assets/124819426/978cd63a-81ea-4c13-9888-e0f5bd6eba7a)

**Closed** 2023-09-20 08:04 UTC
Labels: bug, uat, sev-medium
